package com.my.vaadinDemo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CustomerDesignForm extends FormLayout {
	protected TextField firstName;
	protected TextField lastName;
	protected TextField email;
	protected NativeSelect<com.my.vaadinDemo.CustomerStatus> status;
	protected DateField birthday;
	protected HorizontalLayout hlayout;
	protected Button save;
	protected Button delete;

	public CustomerDesignForm() {
		Design.read(this);
	}
}
